### PR TITLE
fix #4: Add license and test script

### LINKED ISSUE #4: Missing license?
A related warning in `dreamtt.opam` when adding the package:

```text
error 22: Some fields are present but empty; remove or fill them: "license"
```

### PR DESCRIPTION
**Pull request by anqur**
* Add `Apache-2.0` license
* Silence opamch
* Add a test script from 😎tt

### CODE REVIEW

**Comment by jonsterling** [comment]
Cool, thanks! But perhaps we should add a frontend so that this test script can actually run 😄 

I've opened a ticket (#6) if you are interested! Also happy to merge the license change first if you prefer.

**Comment by anqur** [comment]
> Cool, thanks! But perhaps we should add a frontend so that this test script can actually run 😄
> 
> I've opened a ticket (#6) if you are interested! Also happy to merge the license change first if you prefer.

Yes! I was considering to finish #1 but at first silence some warnings from `opam` by this PR, I'm almost new to OCaml and such so I could self-educationally do some stuff following the tickets!

**Comment by jonsterling** [comment]
OK! We can treat this test script as “aspirational” for now 😎😀

**Review by jonsterling — APPROVED** [review]

**Comment by jonsterling** [comment]
I’ve merged this now, thanks for your contribution! And let me know if you need any help navigating the code or have questions about anything, ocaml, etc.

**Pull request merged**
